version: '3.8'

services:
  localai:
    image: localai-custom
    container_name: localai
    environment:
      PRELOAD_MODELS: '[{"url":"file:///models/phi3-light.yaml"}]'
      THREADS: '4'
      NO_GALLERY: 'true'
      REBUILD: 'true'
      LLAMA_CPP_PATH: '/llama.cpp/build/bin/llama-server'  # Ruta al binario compilado
      LOG_LEVEL: 'debug'
      LOCALAI_EXTERNAL_BACKENDS: "llama-cpp"
    volumes:
      - ./models:/models
      - ./llama.cpp:/llama.cpp
    ports:
      - "8080:8080"

  sophie_webhook:
    build: .
    container_name: sophie_webhook
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      LOCALAI_API: http://localai:8080/v1/chat/completions
    depends_on:
      - localai
